# Generated by Django 4.1.2 on 2022-10-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Submodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=10)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('model_submodel', models.CharField(max_length=20)),
                ('transmission_type', models.CharField(choices=[('4A', 'Four-speed automatic transmission'), ('5A', 'Five-speed automatic transmission'), ('6A', 'Six-speed automatic transmission'), ('4M', 'Four-speed manual transmission'), ('5M', 'Five-speed manual transmission'), ('6M', 'Six-speed manual transmission')], max_length=2)),
                ('fuel_system_type', models.CharField(choices=[('p', 'Patrol'), ('d', 'Disel'), ('g', 'Gas')], max_length=1)),
                ('fuel_consumption_requirements', models.DecimalField(decimal_places=1, max_digits=2)),
                ('market_prise', models.IntegerField()),
                ('avarege_to_prise', models.IntegerField()),
                ('avarege_battery_prise', models.IntegerField()),
                ('avarege_tires_prise', models.IntegerField()),
                ('avarege_maintenance_prise', models.IntegerField()),
                ('amortization_period', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads')),
                ('submodel_description', models.TextField(max_length=100)),
            ],
        ),
    ]
