# Generated by Django 4.1.2 on 2022-10-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_submodels',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=2),
            preserve_default=False,
        ),
    ]
