# Generated by Django 4.1.2 on 2022-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_remove_model_submodels_model_submodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_submodels',
            name='avarege_maintenance_prise',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
