# Generated by Django 4.1.2 on 2022-10-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_model_submodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_submodels',
            name='image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
