# Generated by Django 4.1.2 on 2022-10-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_alter_model_submodels_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_submodels',
            name='transmission_type',
            field=models.CharField(choices=[('Four-speed automatic transmission', '4A'), ('Five-speed automatic transmission', '5A'), ('Six-speed automatic transmission', '6A'), ('Four-speed manual transmission', '4M'), ('Five-speed manual transmission', '5M'), ('Six-speed manual transmission', '6M')], max_length=50),
        ),
    ]
