# Generated by Django 4.1.2 on 2022-10-29 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_alter_model_submodels_transmission_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_submodels',
            name='fuel_system_type',
            field=models.CharField(choices=[('Patrol', 'p'), ('Disel', 'd'), ('Gas', 'g')], max_length=10),
        ),
    ]
