# Generated by Django 4.1.2 on 2022-10-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_model_submodels_fuel_cost_without_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_submodels',
            name='submodel_description',
            field=models.CharField(max_length=100),
        ),
    ]
